### ISSUE TITLE
More than one errors

### ISSUE THREAD

**Issue by ghost** [Nearata/flarum-ext-minecraft-avatars#2]
I found the error very difficult. While the extension was active, it gave multiple errors.
```
Notice: Undefined index: minotar in /var/www/sourceturk/flarum/vendor/nearata/flarum-ext-minecraft-avatars/src/Listeners/SaveUserMinotar.php on line 13

Fatal error: Uncaught Laminas\HttpHandlerRunner\Exception\EmitterException: Output has been emitted previously; cannot emit response in /var/www/sourceturk/flarum/vendor/laminas/laminas-httphandlerrunner/src/Exception/EmitterException.php:24 Stack trace: #0 /var/www/sourceturk/flarum/vendor/laminas/laminas-httphandlerrunner/src/Emitter/SapiEmitterTrait.php(40): Laminas\HttpHandlerRunner\Exception\EmitterException::forOutputSent() #1 /var/www/sourceturk/flarum/vendor/laminas/laminas-httphandlerrunner/src/Emitter/SapiEmitter.php(27): Laminas\HttpHandlerRunner\Emitter\SapiEmitter->assertNoPreviousOutput() #2 /var/www/sourceturk/flarum/vendor/laminas/laminas-httphandlerrunner/src/RequestHandlerRunner.php(98): Laminas\HttpHandlerRunner\Emitter\SapiEmitter->emit() #3 /var/www/sourceturk/flarum/vendor/flarum/core/src/Http/Server.php(42): Laminas\HttpHandlerRunner\RequestHandlerRunner->run() #4 /var/www/sourceturk/flarum/public/index.php(26): Flarum\Http\Server->listen() #5 {main} thrown in /var/www/sourceturk/flarum/vendor/laminas/laminas-httphandlerrunner/src/Exception/EmitterException.php on line 24
```

**Comment by Nearata** [comment]
Hi @northeaster ,

I'm not able to reproduce this but, in the meantime i released a new version with a possible fix.

**Comment by owoki** [comment]
I am @northeaster 's friend. The problem is solved now.

**Comment by Nearata** [comment]
Good to know!

**Comment by Zerguine** [comment]
Dosnot work enymore ??
